const HeroSynergyInfo = {
    "": [],
    "Aatrox": ["Shimmerscale", "Warrior"],
    "Ezreal": ["Swiftshot", "Tempest"],
    "Heimerdinger": ["Mage", "Trainer"],
    "Karma": ["Dragonmancer", "Jade"],
    "Leona": ["Guardian", "Mirage"],
    "Nidalee": ["Astral", "Shapeshifter"],
    "Sejuani": ["Guild", "Cavalier"],
    "Senna": ["Cannoneer", "Ragewing"],
    "Sett": ["Dragonmancer", "Ragewing"],
    "Skarner": ["Astral", "Bruiser"],
    "TahmKench": ["Bruiser", "Revel"],
    "Taric": ["Guardian", "Jade"],
    "Vladimir": ["Astral", "Mage"],
    "Ashe": ["Dragonmancer", "Jade", "Swiftshot"],
    "Braum": ["Guardian", "Scalescorn"],
    "Gnar": ["Jade", "Shapeshifter"],
    "Jinx": ["Cannoneer", "Revel"],
    "Kayn": ["Assassin", "Ragewing", "Shimmerscale"],
    "Lillia": ["Cavalier", "Mage", "Scalescorn"],
    "Nami": ["Astral", "Mage", "Mystic"],
    "Qiyana": ["Assassin", "Tempest"],
    "Shen": ["Bruiser", "Ragewing", "Warrior"],
    "Thresh": ["Guardian", "Whispers"],
    "Tristana": ["Cannoneer", "Trainer"],
    "Twitch": ["Guild", "Swiftshot"],
    "Yone": ["Mirage", "Warrior"],
    "Anivia": ["Evoker", "Jade", "Legend"],
    "Diana": ["Assassin", "Scalescorn"],
    "Elise": ["Shapeshifter", "Whispers"],
    "Illaoi": ["Astral", "Bruiser"],
    "LeeSin": ["Dragonmancer", "Tempest"],
    "Lulu": ["Evoker", "Mystic", "Trainer"],
    "Nunu": ["Cavalier", "Mirage"],
    "Olaf": ["Bruiser", "Scalescorn", "Warrior"],
    "Ryze": ["Guild", "Mage"],
    "Swain": ["Dragonmancer", "Ragewing", "Shapeshifter"],
    "Sylas": ["Bruiser", "Mage", "Whispers"],
    "Varus": ["Astral", "Swiftshot"],
    "Volibear": ["Dragonmancer", "Legend", "Shimmerscale"],
    "Corki": ["Cannoneer", "Revel"],
    "Hecarim": ["Cavalier", "Ragewing"],
    "Neeko": ["Jade", "Shapeshifter"],
    "Ornn": ["Bruiser", "Legend", "Tempest"],
    "Sona": ["Evoker", "Revel"],
    "Talon": ["Guild", "Assassin"],
    "Xayah": ["Ragewing", "Swiftshot"],
    "Bard": ["Bard", "Guild", "Mystic"],
    "Pyke": ["Assassin", "Whispers"],
    "Soraka": ["Starcaller", "Jade"],
    "Yasuo": ["Dragonmancer", "Mirage", "Warrior"],
    "Zoe": ["Spell Thief", "Mage", "Shimmerscale"],
    "Daeja": ["Dragons", "Mirage"],
    "Idas": ["Dragons", "Shimmerscale"],
    "ShiOhYu": ["Dragons", "Jade", "Mystic"],
    "Syfen": ["Dragons", "Whispers", "Bruiser"],
    "AoShin": ["Dragons", "Tempest"],
    "AurelionSol": ["Dragons", "Astral", "Evoker"],
    "Shyvana": ["Dragons", "Ragewing", "Shapeshifter"]
}

export default HeroSynergyInfo