const SynergyInfo = {
    "Astral": [[0, "darken"], [3, "bronze"], [6, "gold"], [9, "chromatic"]],
    "Guild": [[1, "bronze"], [2, "bronze"], [3, "silver"], [4, "silver"], [5, "gold"], [6, "chromatic"], [7, "chromatic"]],
    "Jade":  [[3, "bronze"], [6, "silver"], [9, "gold"], [12, "chromatic"]],
    "Mirage": [[2, "bronze"], [4, "silver"], [6, "gold"], [8, "chromatic"]],
    "Ragewing": [[3, "bronze"], [6, "silver"], [9, "gold"]],
    "Revel": [[2, "bronze"], [3, "silver"], [4, "gold"], [5, "chromatic"]],
    "Scalescorn": [[2, "bronze"], [4, "gold"], [6, "chromatic"]],
    "Shimmerscale": [[3, "bronze"], [5, "silver"], [7, "gold"], [9, "chromatic"]],
    "Tempest": [[2, "bronze"], [4, "silver"], [6, "gold"], [8, "chromatic"]],
    "Trainer": [[1, "bronze"], [3, "gold"]],
    "Whispers": [[2, "bronze"], [4, "silver"], [6, "gold"], [8, "chromatic"]],
    "Assassin": [[2, "bronze"], [4, "gold"], [6, "chromatic"]],
    "Bard": [[1, "gold"]],
    "Bruiser": [[2, "bronze"], [4, "silver"], [6, "gold"], [8, "chromatic"]],
    "Cannoneer": [[2, "bronze"], [3, "silver"], [4, "gold"], [5, "chromatic"]],
    "Cavalier": [[2, "bronze"], [3, "silver"], [4, "gold"], [5, "chromatic"]],
    "Dragons": [[1, "gold"], [2, "darken"]],
    "Dragonmancer": [[3, "bronze"], [6, "gold"], [9, "chromatic"]],
    "Evoker": [[2, "bronze"], [4, "gold"], [6, "chromatic"]],
    "Guardian": [[2, "bronze"], [4, "gold"], [6, "chromatic"]],
    "Legend": [[3, "gold"]],
    "Mage": [[3, "bronze"], [5, "silver"], [7, "gold"], [9, "chromatic"]],
    "Mystic": [[2, "bronze"], [3, "silver"], [4, "gold"], [5, "chromatic"]],
    "Shapeshifter": [[2, "bronze"], [4, "silver"], [6, "gold"]],
    "Spell Thief": [[1, "gold"]],
    "Starcaller": [[1, "gold"]],
    "Swiftshot": [[2, "bronze"], [4, "gold"], [6, "chromatic"]],
    "Warrior": [[2, "bronze"], [4, "gold"], [6, "chromatic"]]
};

export default SynergyInfo;